export const apiEndpoint = (baseUrlAPI: any) => ({
  AUTHENTICATION: {
    LOGIN: `${baseUrlAPI}/api/auth/login`,
    REGISTER: `${baseUrlAPI}/api/auth/register`,
    REGISTER_VERIFY: `${baseUrlAPI}/api/auth/register-verify`,
    FORGET_PASSWORD: `${baseUrlAPI}/api/auth/forget-password`,
    FORGET_PASSWORD_VERIFY: `${baseUrlAPI}/api/auth/forget-password-verify`,
    CHANGE_PASSWORD: `${baseUrlAPI}/api/auth/change-password`,
    FORGET_PASSWORD_VERIFY_CODE: `${baseUrlAPI}/api/auth/forget-password-verify-code`,
  },
  USER: {
    PROFILE: `${baseUrlAPI}/api/User/profile`,
    UPDATE_PROFILE: `${baseUrlAPI}/api/User/update-profile`,
    GET_POINTS: `${baseUrlAPI}/api/User/GetPoints`,
    HISTORIES_POINTS: `${baseUrlAPI}/api/User/GetPointHistories`,
    HISTORIES_SERVICES: `${baseUrlAPI}/api/User/get-all-history-services`,
    GET_NOTIFICATIONS: `${baseUrlAPI}/api/User/get-all-notifications`,
    READ_NOTIFICATIONS: `${baseUrlAPI}/api/User/read-notifications`,
    CLICK_NOTIFICATIONS: `${baseUrlAPI}/api/User/click-notification`,
    DELETE_ACCOUNT: `${baseUrlAPI}/api/User/DeleteAccount`,
  },
  TRIP: {
    GET_CITY: `${baseUrlAPI}/api/Trip/GetCity`,
    GET_PLACES: `${baseUrlAPI}/api/Trip/GetAllPlaces`,
    GET_VEHICLE_TYPES: `${baseUrlAPI}/api/Trip/GetVehicleTypes`,
    SEARCH_ROUTE: `${baseUrlAPI}/api/Trip/SearchRoute`,
    SEARCH_ROUTE_V2: `${baseUrlAPI}/api/Trip/SearchRoutev2`,
    RESERVATION_START: `${baseUrlAPI}/api/Trip/ReservationStart`,
    GET_TRIP_RESERVED_SEATS: `${baseUrlAPI}/api/Trip/GetTripReservedSeats`,
    RESERVATION_VALIDATE_SEATS: `${baseUrlAPI}/api/Trip/ReservationValidateSeats`,
    GET_TRIP_START_PLACES: `${baseUrlAPI}/api/Trip/GetTripStartPlaces`,
    GET_TRIP_END_PLACES: `${baseUrlAPI}/api/Trip/GetTripEndPlaces`,
    RESERVATION_UPDATE_INFO: `${baseUrlAPI}/api/Trip/ReservationUpdateInfo`,
    RESERVATION_CONFIRM_PAYMENT: `${baseUrlAPI}/api/Trip/ReservationConfirmPayment`,
    GET_TICKET_INFO: `${baseUrlAPI}/api/Trip/GetTicketInfo`,
    CANCEL_BATCH: `${baseUrlAPI}/api/Trip/CancelBatch`,
    GET_BANK: `${baseUrlAPI}/api/Trip/GetBankInfo`,
  },
  NEWS: {
    GET_BLOG_HOST: `${baseUrlAPI}/api/Blog/GetHighlightBlogs`,
    GET_BLOG_LIST: `${baseUrlAPI}/api/Blog/GetBlogList`,
    GET_BLOG_DETAIL_ID: `${baseUrlAPI}/api/Blog/GetBlogDetail`,
    GET_BLOG_NEWS: `${baseUrlAPI}/api/Blog/GetNewestBlogs`,
    GET_BLOG_DETAIL_URL: `${baseUrlAPI}/api/Blog/GetBlogByUrl`,
  },
  SHIPMENT: {
    GET_SHIPPING_ORDER_DETAIL: `${baseUrlAPI}/api/Shipment/GetShippingOrderDetail`,
    GET_SHIPMENT_LOCATION: `${baseUrlAPI}/api/Shipment/GetShipmentLocation`,
    CREATE_SHIPMENT_ORDER: `${baseUrlAPI}/api/Shipment/CreateShippingOrder`,
    GET_PACKAGE_TYPES: `${baseUrlAPI}/api/Shipment/GetPackageTypes`,
    GET_PACKAGE_WEIGHT: `${baseUrlAPI}/api/Shipment/GetPackageWeights`,
    GET_PACKAGE_DIMENSIONS: `${baseUrlAPI}/api/Shipment/GetPackageDimensions`,
    GET_PACKAGE_COST: `${baseUrlAPI}/api/Shipment/GetShipmentCost`,
  },
  VEHICLE: {
    CREATE_VEHICLE: `${baseUrlAPI}/api/VehicleRental/CreateRentalContract`,
    GET_VEHICLE_DETAIL: `${baseUrlAPI}/api/VehicleRental`,
  },
  VOUCHER: {
    GET_ALL_VOUCHERS: `${baseUrlAPI}/api/Trip/GetAllVouchers`,
  },
});
